# -*- coding: utf-8 -*-
"""LinearRegression_lesson01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HBmuIVS9FnLiUK-h8tA988cuElc0R2Ux
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

df=pd.read_csv("homeprices.csv")
df

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')

reg=linear_model.LinearRegression()
reg.fit(df[['area']],df.price)

reg.predict([[3300]])

reg.coef_

reg.intercept_

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('area')
plt.ylabel('price')
plt.scatter(df.area,df.price,color='red',marker='+')
plt.plot(df.area,reg.predict(df[['area']]),color='blue')



d=pd.read_csv("areas.csv")
d.head(3)

p=reg.predict(d)
p

d['prices']=p

d.to_csv("prediction.csv",index=False)

c=pd.read_csv("canada_per_capita_income.csv")
c.head(50)

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('income')
plt.scatter(c['year'], c['per capita income (US$)'], color='red', marker='+')

reg2=linear_model.LinearRegression()
reg2.fit(c[['year']],c['per capita income (US$)'])

reg2.predict([[2024]])

new_years=pd.DataFrame({'year': np.arange(2017,2025)})
new_years

new_years['per capita income (US$)']=reg2.predict(new_years[['year']])
new_years

c_extend=pd.concat([c,new_years],ignore_index=True)

c_extend.to_csv("canada_per_capita_income.csv",index=False)

c_extend

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('income')
plt.scatter(c['year'],c['per capita income (US$)'],color='red',marker='+')
plt.plot(c['year'],reg2.predict(c[['year']]),color='blue')
plt.xlim(c['year'].min(), 2027)
plt.grid(True)
plt.show()